name: restaurant_app
description: "Restaurant App with Dicoding API"
publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.1.2
  d_method: ^0.2.6
  provider: ^6.1.2
  google_fonts: ^6.2.1
  loading_animation_widget: ^1.2.1
  cached_network_image: ^3.3.1
  logger: ^2.4.0
  sqflite: ^2.3.3+1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.1.0
  rxdart: ^0.27.7
  android_alarm_manager_plus: ^3.0.3
  intl: ^0.19.0
  device_info_plus: ^9.1.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/menu/restaurant-active.png
    - assets/menu/restaurant-inactive.png
    - assets/menu/setting-active.png
    - assets/menu/setting-inactive.png


    - assets/icon-location.png
    - assets/icon-no-internet.png
    - assets/icon-rating.png
    - assets/icon-search.png
    - assets/broken-image.png
    - assets/no-data.png
    - assets/food.png
    - assets/boy.png
    - assets/success.png

